from models.networks.detection.zheng_cvpr2019_dsdnet import DSDGenerator
from models.networks.detection.zhu_eccv2018_bdrar import BDRARGenerator
from models.networks.removal.le_iccv2019_spmnet import SPMGenerator
